<calculator 
	calculatortitle="{{ $siteWide->getText('site_breed.calculator_titel') }}"
	bonus="{{ $siteWide->getText('site_breed.bonus') }}"
	interest="{{ $siteWide->getText('site_breed.interest') }}"
	investment="{{ $siteWide->getText('site_breed.investment') }}"
	andor="{{ $siteWide->getText('site_breed.and_or') }}"
	url="{{ $app_url }}"
	amountbriqs="{{ $siteWide->getText('site_breed.amount_briqs') }}"
	month="{{ $siteWide->getText('site_breed.month') }}"
	year="{{ $siteWide->getText('site_breed.year') }}"
	fiveyears="{{ $siteWide->getText('site_breed.return_5_year') }}"
	redeem="{{ $siteWide->getText('site_breed.redeem') }}"
	exclusive="{{ $siteWide->getText('site_breed.exclusive') }}"
	rights="{{ $siteWide->getText('site_breed.rights') }}"
	buybriqs="{{ $siteWide->getText('site_breed.buy_briqs') }}"
	monthlyinvestment="{{ $siteWide->getText('site_breed.monthly_investment') }}"
	reinvestinterest="{{ $siteWide->getText('site_breed.reinvest_interest') }}"
></calculator>